apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2020-07-27T09:59:31Z"
  generation: 2
  name: configurations.appconnect.ibm.com
  resourceVersion: "76672548"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/configurations.appconnect.ibm.com
  uid: 10d1ed69-1bc2-4d5a-bdfd-7198ca6d4aa4
spec:
  conversion:
    strategy: None
  group: appconnect.ibm.com
  names:
    categories:
    - all
    - ace
    - cp4i
    kind: Configuration
    listKind: ConfigurationList
    plural: configurations
    singular: configuration
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: IBM App Connect Operator provides the ability to create configurations
          for use with integration servers. For information about the installation
          parameters, see http://ibm.biz/aceconfig.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: "ConfigurationSpec is the schema for a exactly one configuration
              item. \n ***Note that the custom resource definition is **unable** to
              restrict this, since Kubernetes does not allow the use of `minProperties`
              and `maxProperties` \n This may represent one of several different kinds
              of configuration resource; - odbc - policyproject - serverconf - setdbparms
              - generic - truststore - keystore - accounts - agentx \n A single integration
              defined in a BAR file may use one or more of these. \n Each resource
              kind is modelled in `Configuration` definition as a different field
              - so a single `configuration` item must have exactly one of those fields
              set. \n A subset of the resources contain confidential information such
              as passwords - they are; - keystore - accounts - extensions.zip - setdbparms.txt
              - truststore - agentx.json \n In these cases, the main resource content
              is held in a Kubernetes secret, and is represented in this object as
              a reference to the secret. The secret is currently restricted to be
              in the same namespace."
            properties:
              contents:
                description: Base64 encoded (non-secret) contents of the configuration
                  file - do not set secrets in this field
                type: string
              data:
                description: Base64 encoded contents of the configuration file - will
                  be moved by the operator to either a secret or the contents field.
                enum:
                - dataShouldAlwaysBeMutatedIntoSecretOrContents
                type: string
              description:
                type: string
              secretName:
                description: A reference to the kubernetes secret that holds the configuration
                  file contents
                type: string
              type:
                type: string
              version:
                description: This field is populated by the App Connect Operator,
                  and does not require manual input.
                pattern: ^(\d+)\.(\d+)\.(\d+)\.(\d+)\-r(\d)$
                type: string
            required:
            - type
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - all
    - ace
    - cp4i
    kind: Configuration
    listKind: ConfigurationList
    plural: configurations
    singular: configuration
  conditions:
  - lastTransitionTime: "2020-07-27T09:59:31Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-07-27T09:59:31Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
