apiVersion: v1
kind: Service
metadata:
  name: dp-remote-apicgw-mgmt
spec:
  type: ClusterIP
  ports:
  - name: webmgmt
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: gws
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: apiep
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: apigw-apigwv5